# Usar la imagen base de Node.js
FROM node:19.2-alpine3.17

# Establecer el directorio de trabajo en el contenedor
# CD /usr/src/app
WORKDIR /usr/src/app

# Copiar el archivo package.json y package-lock.json al directorio de trabajo
COPY app.js package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos de la aplicación al contenedor
COPY . .

# ejecutar el testing
RUN npm run test

# eliminar archivos no necesarios en PROD
RUN rm -rf test && rm -rf node_modules

# Instalar solo nodemodules de PROD
RUN npm install --prod


# Exponer el puerto en el que la aplicación va a estar escuchando
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]